### ISSUE TITLE
counter does not work properly on images

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/DataStructures.jl#107]
The root of this problem likely has nothing to do with images, but:

`img = Image(fill(Color.color("blue"), (3,3)))`
`counter([img, img])`

yields

`Accumulator{RGB{Float64},Int64}([RGB{Float64}(0.0,0.0,1.0)=>18])`

It seems to iterate over the individual pixels, rather than over the images. Dicts do not have this issue, as I can build a counter with `d = DefaultDict(0); for im=[img, img] d[im]+=1 end` and it works fine.

**Comment by kmsquire** [comment]
@cstjean, the problem is that `[img, img]` concatenates arrays together, and images are really just fancy arrays:

```julia
julia> img = Image(fill(Color.color("blue"), (3,3)))
RGB Images.Image with:
  data: 3x3 Array{Color.RGB{Float64},2}
  properties:

julia> [img, img]
RGB Images.Image with:
  data: 6x3 Array{Color.RGB{Float64},2}
  properties:
```

In Julia v0.4, this will give a warning, and in Julia v0.5, this syntax will no longer concatentate.

Until then, there are various ways to work around this for now.  One way is to give the array a type:

```julia
julia> imgs = Image[img, img]
2-element Array{Images.Image{T,N,A<:AbstractArray{T,N}},1}:
 RGB Images.Image with:
  data: 3x3 Array{Color.RGB{Float64},2}
  properties:
 RGB Images.Image with:
  data: 3x3 Array{Color.RGB{Float64},2}
  properties:

julia> counter(imgs)
DataStructures.Accumulator{Images.Image{T,N,A<:AbstractArray{T,N}},Int64}(Dict{Images.Image{T,N,A<:AbstractArray{T,N}},Int64}(RGB Images.Image with:
  data: 3x3 Array{Color.RGB{Float64},2}
  properties:=>2))
```
