### ISSUE TITLE
Use Sphinx documentation

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/DataStructures.jl#108]
As the package grows and more data structures come in, it becomes cumbersome to use a single readme page to host all the documentation. 

I propose to convert the documentation to Sphinx (similar to that in the Distributions package), and host the documentation on [ReadTheDocs](https://readthedocs.org).

If there's no objection, I would make a PR later this week.

**Comment by kmsquire** [comment]
+1

**Comment by hayd** [comment]
I think I'll put something together here soon, hopefully using the new Docile rewrite, which generates markdown (rather than rst) documentation from docstrings so it can then be built e.g. with mkdocs.

The first order of business is documenting every method with the 0.4 syntax.

**Comment by StephenVavasis** [comment]
I was the one responsible for switching README from md format to rst format for the DataStructures package.  I made this change because I didn't know how to document a list of functions using md, like this:

  push!(s,i)

Pushes item i onto s

  pop!(s)

Retrieves the last item from s

... and so on.

**Comment by hayd** [comment]
Once the README and documentation is generated from the docstrings it'll mean you don't have to update the documentation/README manually (and copy and paste the documentation for each method), and will remove the possibility the README and the docstrings go out of sync.

Docile will also style the above so you just write (currently; this is not yet released):
```
@{
    push!
    pop!
    ...
}
```
and it'll expand it into markdown documenting these functions.
