### ISSUE TITLE
Stacks and Queues should work in for loops

### ISSUE THREAD

**Issue by RaviMohan** [JuliaLang/DataStructures.jl#116]
Right now Deque works in for loops, but Stacks and Queues don't

```Julia
using DataStructures

s = Stack(Int)
q = Queue(Int)
deq  = Deque{Int}()

for x in deq println(x) end
``` 
works
 
but 
```Julia 
for x in s println(x) end
ERROR: `start` has no method matching start(::Stack{Deque{Int64}})
 in anonymous at no file

julia> for x in q  println(x) end
ERROR: MethodError: `start` has no method matching start(::DataStructures.Queue{DataStructures.Deque{Int64}})
 in anonymous at no file
```

I think this is because Stack and Queue, while building on Deque, don't redefine next() etc required for iteration. I thought they'd use the underlying Deque's itrerator protocol [1], but apparently not.

[1]which would still be wrong for one of Stack or Queue or both -if Deque uses random access for iteration - Stack iteration should be LIFO and Queue should have FIFO iteration

**Comment by kmsquire** [comment]
The assumption might be that typically, stacks and queues are used as, well, stacks and queues, and iterating over them isn't common.  But I don't see a problem with it per se.

Care to take a stab at implementing this and submitting a PR?

**Comment by ViralBShah** [comment]
I think it would be a nice convenience to have, even though it is not common.

**Comment by RaviMohan** [comment]
Yes I get that argument. STL works the same way. 

But there is a counter argument to be made that any "sequence like" data structure should have an iterator/iterator like behaviour. Java and Scala for e.g do provide iterators  (1) (though Java screws it up in style by giving a Stack a FIFO iterator ! Par for the course for Java. At least they acknowledge it is a design mistake (2))

Sure I'll be glad to take a crack at it and submit a PR . Thanks.

[1] From the [Scala documentation] (http://www.scala-lang.org/api/current/index.html#scala.collection.mutable.Stack)

def iterator: Iterator[A]

Returns an iterator over all elements on the stack. This iterator is stable with respect to state changes in the stack object; i.e. such changes will not be reflected in the iterator. The iterator issues elements in the reversed order they were inserted into the stack (LIFO order). 

[2] [this bug report](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4475301)

**Comment by lindahua** [comment]
Stacks and Queues are not *sequences*. Such data structures are there for very specific purposes (stacks for FILO access while queues for FIFO access).

I understand that sometimes people want to inspect all the elements stored internally, for debugging or other purposes. However, for certain data structures, it unclear what the *default* traverse order should be. To support such use, we can provide a several `iter` functions that returns an iterable collection out of a stack or a queue:

```julia
# let s be a stack
for v in forward_iter(s)  # from bottom to top
    # ...
end

for v in backward_iter(s)   # from top to bottom (that's how call-stacks are typically traversed)
    # ...
end
```

The ``iter`` can be just a light-weight wrapper of the stack/queue, or it can simply return the underlying array.

BTW: I think we should have such multiple kinds of iterators for other data structures (*e.g.* trees have pre-order, in-order, post-order, etc).

**Comment by RaviMohan** [comment]
Sure they "are not" sequences. I was careful to use the words "sequence like" and that within quotes. 

What I meant was that you could view them as having sequence like behaviour in specific contexts  - like iterating through the contents in a for loop. Instead of  "sequence like" I should perhaps have used  "Iterable" . Thus you have trees being "Iterables"  - ie they can be iterated through- with multiple possible iterators with different navigation strategies. 

Stacks and Queues are (imho) Iterables.

As you rightly say "for v in backward_iter(s) #from top to bottom (that's how call-stacks are typically traversed)" which seems to  me to imply that the default iterator/iteration behaviour should be LIFO for Stacks and FIFO for queues. 

At the code/implementation level whether the datastructure adheres to an Iterables protocol (next, done, start in Julia) ie they 'are iterables and have a default iteration behaviour' or 'return an iterable collection via an explicit call to one of many  possible iter_functions' seems to be a minor distinction to me (but then I'm not  all that fluent in Julia, maybe one or the other fits better into the Julia way). 

 I prefer the former because it is conceptually simpler for the user *for Stack and Queue*,  but it is not  a big deal if the user has  to call a separate 'give me an iterable collection'  function and use the result of that call in the for loop. For data structures that *don't* have an obvious default order, it makes  sense to have x_iter() , y_iter() etc functions.

My 'ask' in raising the issue is that stacks and queues provides *some* way for its user to iterate through it in a for loop. If it is an uncommon use case for Stacks and Queues, we could leave things as they are.

**Comment by RaviMohan** [comment]
Can someone help me decipher the Stack type declaration?

```Julia
using DataStructures
julia> s = Stack(Real,5)
DataStructures.Stack{DataStructures.Deque{Real}}(Deque [Real[]])
```
That's a strange type signature for something so simple. Stack is parametrized by Deque{Real} ?

 So I look into the source code and see

```Julia
type Stack{S}   # S is the type of the internal dequeue instance
    store::S
end

Stack{T}(ty::Type{T}) = Stack(Deque{T}())
Stack{T}(ty::Type{T}, blksize::Integer) = Stack(Deque{T}(blksize))
```

The parameter for the type Stack seems to be  Deque{T}. Surely that should be {T}.  Something like 
```Julia
type MyStack{T}

    store::Deque{T}
    
    function MyStack()
        new(Deque{T}())
    end

    function MyStack(initialCapacity::Int)
        new(Deque{T}(initialCapacity))
    end

end
```

seems a bit better. put that in a file  and sure enough 

```Julia
julia> include("mystack.jl")


julia> st  = MyStack{Real}(5)
MyStack{Real}(Deque [Real[]])

```

What am I missing here? (I haven't got my head completely around Julia's type system yet and am going by what I would declare in SML say. Any assistance greatly appreciated)

**Comment by RaviMohan** [comment]
aargh I closed this accidentally.  Sorry .

**Comment by Evizero** [comment]
This addition is really great and I could really use it in my package. Could someone tag a new version?

**Comment by eschnett** [comment]
`Stack::iter` uses `unshift!` on arrays, which is very expensive. It would be cheaper to use `push!`, and then to `reverse` the array.

**Comment by kmsquire** [comment]
A bit of a late response, but I believe that `unshift!` and `push!` have the same amortized cost.  As with `push!`, `unshift!` increase the size of the backing array (I think it still doubles), and leave space at the front for the array to grow:

```julia
julia> x = rand(2^20);

julia> @time unshift!(x, .1);
  0.003865 seconds (5 allocations: 8.000 MB, 74.99% gc time)

julia> @time unshift!(x, .1);
  0.000002 seconds (4 allocations: 160 bytes)

julia> y = rand(2^20);

julia> @time push!(y, .1);
  0.000428 seconds (5 allocations: 8.000 MB)

julia> @time push!(y, .1);
  0.000002 seconds (4 allocations: 160 bytes)

julia> @time push!(y, .1);
  0.000002 seconds (4 allocations: 160 bytes)
```

Initial times are after warm up of `push!` and `unshift!`.
