### ISSUE TITLE
Test failing on checking out and running tests.

### ISSUE THREAD

**Issue by RaviMohan** [JuliaLang/DataStructures.jl#117]
I forked DataStructures.jl , checked out,  and did
```shell
ravi@hod:~/juliastackhack/DataStructures.jl$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
ravi@hod:~/juliastackhack/DataStructures.jl$ cd test

julia runtests.jl
/home/ravi/juliastackhack/DataStructures.jl/test/test_deque.jl ...
WARNING: module DataStructures should explicitly import < from Base
WARNING: module DataStructures should explicitly import <= from Base
/home/ravi/juliastackhack/DataStructures.jl/test/test_sortedcontainers.jl ...
ERROR: LoadError: LoadError: UndefVarError: pastendsemitoken not defined
 in test1 at /home/ravi/juliastackhack/DataStructures.jl/test/test_sortedcontainers.jl:281
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:263
 in anonymous at no file:19
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:263
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/ravi/juliastackhack/DataStructures.jl/test/test_sortedcontainers.jl, in expression starting on line 1529
while loading /home/ravi/juliastackhack/DataStructures.jl/test/runtests.jl, in expression starting on line 16

```
The two WARNING s seem worthy of being looked at as well. Please let me know if I'm doing something incorrectly. AFAIK this is the way to run tests for Julia packages.

**Comment by aviks** [comment]
You look to be running the tests on a recent `0.4-dev` version of Julia. It may be that this package does not support `0.4` fully yet?

**Comment by RaviMohan** [comment]
Hmm. I built from  source from master.  Is there a way of finding out (from the Package manager perhaps) which version a package should be built against?

**Comment by RaviMohan** [comment]
I had 0.3.2 on an old laptop and it works there. Closing this. Thanks for the pointer :-) (still be nice to know which version a package expects)

**Comment by aviks** [comment]
`master` is `0.4`. There is a `release-0.3` branch which is the last stable release...

>Is there a way of finding out (from the Package manager perhaps) which version a package should be built against?

There is http://pkg.julialang.org/?pkg=DataStructures&ver=release
