### ISSUE TITLE
move ahead on #126?

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/DataStructures.jl#132]
Dear @kmsquire and @lindahua,

I have merged my pull request #126 and squashed the commits.  Can we move ahead on merging it into master?  It fixes an actual bug in SortedMultiDict, as well as providing many updates to improve compatibility with new features of 0.4 and 0.5.

Thanks,
Steve

**Comment by kmsquire** [comment]
Done. A new version needs to be tagged.

**Comment by danielarndt** [comment]
@kmsquire @StephenVavasis can this be closed?

**Comment by StephenVavasis** [comment]
OK with me to close.  However, I notice that the last tagged version is rather far behind the current master, and furthermore there are a few outstanding PR's.

**Comment by danielarndt** [comment]
@StephenVavasis I'd love a new tag, it would eliminate some warnings over here..

**Comment by StephenVavasis** [comment]
AFAIK I do not have adequate permission to make a new tagged version.  I think that @kmsquire and @lindahua both have adequate permission.
