### ISSUE TITLE
missing default constructor for SortedDict,SortedMultiDict, SortedSet

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/DataStructures.jl#134]
The SortedDict, SortedMultiDict, and SortedSet types are missing the default constructors, and I'm not sure how to write them.In other words, the following code gives an error about a missing constructor:

``` julia
   s = SortedDict{Int, Int}()
```

(There are other ways to construct an empty SortedDict, for instance `s=SortedDict(Dict{Int,Int}())`, but the above would be the most natural.) Any suggestions?  The relevant source code is in sortedDict.jl.  I am embarrassed that I still don't understand this!

Edit (3 hours later): For further clarification: I am able to create a sorteddict by specifying all three type parameters, e.g., 

```
   s = SortedDict{Int, Int, Base.ForwardOrdering}()
```

works, but ideally `SortedDict` will support the same empty-dictionary constructor as `Dict` (and hence choose the default Base.ForwardOrdering for the third type parameter if it is omitted).    But I have not been able to figure out how to do this.

**Comment by kmsquire** [comment]
@StephenVavasis, I had a look at this, and wasn't able to solve it quickly.  I agree that it would be nice to have these types of constructors, though.  Will try to look again later today.
