### ISSUE TITLE
list(x)==list(x) returns false

### ISSUE THREAD

**Issue by lostanlen** [JuliaLang/DataStructures.jl#135]
It looks like list `isequal` only yields the correct answer for empty lists.

```
julia> nil() == nil()
true

julia> list(2,3,4) == list(2,3,4)
false

julia> versioninfo()
Julia Version 0.5.0-dev+238
Commit 5bebf41 (2015-09-17 07:27 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

The reason it that comparison of values `==` falls back to comparison of hashes `===`. Yet list hashes are guaranteed to be the same only when the list is `nil()`.

```
julia> @which list(2,3,4) == list(2,3,4)
==(x, y) at operators.jl:11
```

Is this intended ? If not I can submit a PR to fix this.

**Comment by kmsquire** [comment]
Not intended. A PR would be very welcome!

**Comment by lostanlen** [comment]
Should `nil(T) == nil(S)` imply `T==S` or be true for all types `T` and `S` ? For arrays, `T[] == S[]` yields `true` for all types.
