### ISSUE TITLE
Drop 0.3 support?

### ISSUE THREAD

**Issue by simonster** [JuliaLang/DataStructures.jl#145]
Is it important to people that we maintain 0.3 support, now that 0.4 is out?

**Comment by danielarndt** [comment]
It seems unnecessary to me

**Comment by kmsquire** [comment]
Practically, I think it's reasonable to drop v0.3 support.  Very few people (myself included) are spending much time maintaining this, and the functionality in the current version is pretty reasonable on v0.3 for those that need it.
