### ISSUE TITLE
DefaultDict with Vector{T} value

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/DataStructures.jl#149]
Hi, 

I am using `DefaultDict` with `Int` keys and `Vector{Int}` values. Changing the value of one key, by pushing an element to the vector, changes the values of all keys, as demonstrated below:
   
    julia> rs = DefaultDict(Int, Vector{Int}, Int[])
    DataStructures.DefaultDict{Int64,Array{Int64,1},Array{Int64,1}} with 0 entries

    julia> rs[1]
    0-element Array{Int64,1}

    julia> rs[2]
    0-element Array{Int64,1}

    julia> rs
    DataStructures.DefaultDict{Int64,Array{Int64,1},Array{Int64,1}} with 2 entries:
      2 => Int64[]
      1 => Int64[]

    julia> push!(rs[1], 2)
    1-element Array{Int64,1}:
     2

    julia> rs
    DataStructures.DefaultDict{Int64,Array{Int64,1},Array{Int64,1}} with 2 entries:
      2 => [2]
      1 => [2]

    julia> push!(rs[5], 25)
    2-element Array{Int64,1}:
      2
     25

    julia> rs
    DataStructures.DefaultDict{Int64,Array{Int64,1},Array{Int64,1}} with 3 entries:
      2 => [2,25]
      5 => [2,25]
      1 => [2,25]

Clearly, 

    julia> object_id(rs[1])  
    0xb0533afe255c0575

    julia> object_id(rs[2])
    0xb0533afe255c0575

Is this an intended side effect of the underlying implementation or is it a bug? I will appreciate any possible temporary workaround.

Cheers

**Comment by yuyichao** [comment]
This is [expected, documented with the correct solution provided](https://github.com/JuliaLang/DataStructures.jl#defaultdict-and-defaultordereddict)

**Comment by gasagna** [comment]
My fault.

Thanks
