### ISSUE TITLE
Add Hash Array Mapped Trie

### ISSUE THREAD

**Issue by rawls238** [JuliaLang/DataStructures.jl#150]
Any objections against adding an implementation of hash array mapped tries in this package?

**Comment by kmsquire** [comment]
No objections per se, but as you can see, there aren't many people maintaining this package, so response is a bit slow.

I haven't reviewed the implementation of tries here recently, but if possible, it would be best if you could stick to the associative interface as much as possible (see `http://docs.julialang.org/en/release-0.4/stdlib/collections/#associative-collections)

**Comment by rawls238** [comment]
sounds good @kmsquire, happy to help out maintaining this package if there's a need for it

**Comment by kmsquire** [comment]
@rawls238, help would be great!  Why don't you work on a PR related to this or one of the other open issues, and when all looks good, I'll request commit access for you.

**Comment by rawls238** [comment]
sounds good to me!

**Comment by rawls238** [comment]
Found https://github.com/JuliaLang/FunctionalCollections.jl which contains an implementation of HAMT for persistent hash map, so going to close this issue.

**Comment by kmsquire** [comment]
If someone were ambitious, this would still be welcome here, FWIW.
