### ISSUE TITLE
Cannot Pkg.add DataStructures under windows Julia 0.4

### ISSUE THREAD

**Issue by 2nNguyen** [JuliaLang/DataStructures.jl#151]
This is what I get when I try to install the package:
```
julia> Pkg.add("DataStructures")
ERROR: unsatisfiable package requirements detected: no feasible version could be found for package: WinRPM
 in error at error.jl:21
 in sync_end at task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:46
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23
```

**Comment by kmsquire** [comment]
@2nNguyen, are you still having this problem?

Unfortunately, I don't have access to a Windows machine (and it doesn't look like anyone else following here can help).  `DataStructures` itself doesn't directly require `WinRPM`, and I can't see where that might be pulled in.

Some things to try:
* run `Pkg.update()`, and try again
* run `Pkg.status()`, and see if you have any pinned packages (i.e., packages which show `master` or `dirty` or something else in the third column).  Unpin these and try again

After that, if it still doesn't work, please try posting on the `julia-users` mailing list.

I'm going to close this, but feel free to post back here, and I can reopen if it is actually a `DataStructures.jl` problem
