### ISSUE TITLE
Precompile of DataStructures failing in Julia 0.4.2

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/DataStructures.jl#153]
I'm trying to load the following but I get stuck at DataStructures and hit the error below. Requests also gives me the same error if I reorder them in the using instruction
Any ideas?

--
`using Compat, DataStructures, Requests, JSON, PyPlot, LsqFit, HypothesisTests`

error:

INFO: Precompiling module DataStructures...
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Compat.ji for module Compat.
ERROR: LoadError: unlink: read-only file system (EROFS)
 in unlink at fs.jl:102
 in rm at file.jl:59
 in create_expr_cache at loading.jl:330
 in recompile_stale at loading.jl:461
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/juser/.julia/v0.4/DataStructures/src/DataStructures.jl, in expression starting on line 5

**Comment by kmsquire** [comment]
@ianshmean, sorry not to respond sooner.  Did you ever get past this?

If you follow the error, it looks like at least one of your julia packages (`Compat`) are stored in a location (`/opt/julia_packages`) that you do not have write access to.  How is Julia installed, and how did you install your packages?

It may be that Julia needs to give a better error or deal better with read-only file systems, but that would be a Julia issue.  If you're still having issues, I would suggest first posting a message on `julia-users` describing your situation more, and then, if useful, opening an issue with Julia itself.
