### ISSUE TITLE
no matching method for enqueue!(::Type(DataStructures.Queue{Float32}}, ::Float32)

### ISSUE THREAD

**Issue by crunch3** [JuliaLang/DataStructures.jl#174]
I am a relative Julia neophyte, so maybe this is pilot error, but I have...

```jl
adjCloseMuQ = Queue{Float32};    #outside of a while loop
# some calculations, and 
   enqueue!(adjCloseMuQ,Float32(adjCloseMu));   # inside the loop

# at run time, I get the following error...
MethodError: `enqueue!` has no method matching enqueue!(::Type(DataStructures.Queue{Float32}}, ::Float32)
Closest candidates are:
 enqueue!(::DataStructures.Queue{S}, ::Any)
```
if it's an error in my code, I'd appreciate a suggestion.  If not, perhaps it's a bug...

**Comment by johnmyleswhite** [comment]
Questions like this should go to julia-users.

A hint: ponder the meaning of `adjCloseMuQ = Queue{Float32};` for a while until you realize why you don't want that line in your code.

**Comment by kmsquire** [comment]
Hi @crunch3, try setting `adjCloseMuQ = Queue{Float32}()`--you need the `()` to call the constructor.

Especially as you're starting with Julia, @johnmyleswhite's suggestion of asking on the mailing list is a good one.  Cheers!
