### ISSUE TITLE
Add getindex and find methods to OrderedSet?

### ISSUE THREAD

**Issue by ahwillia** [JuliaLang/DataStructures.jl#178]
I was using OrderedSets and found the following two functions useful:

```julia
getindex(x::OrderedSet,i::Int) = x.dict.keys[x.dict.order[i]]
```

```julia
function find{T}(x::OrderedSet{T},item::T)
    for i in x.dict.order[i]
        x.dict.keys[i] == item && return i
    end
    # item not found... throw error
end
```

I was surprised they weren't already included in this package... Is there a reason behind this?

**edit 1:** It looks like `findin` would be the more appropriate name for the second function

**edit 2:** I understand why `Set` doesn't have these functions defined, but it seems like these should be well defined for an *ordered* set.

**Comment by kmsquire** [comment]
Seems reasonable to me, although I'm not sure your second function is quite right.  

Can you submit a pull request, with some quick tests that verify functionality?

**Comment by rawls238** [comment]
closed by @ahwillia in https://github.com/JuliaLang/DataStructures.jl/pull/180. Thanks @ahwillia!
