### ISSUE TITLE
The files should be named in the same rule?

### ISSUE THREAD

**Issue by sunoru** [JuliaLang/DataStructures.jl#194]
For example, circularbuffer.jl -> circularBuffer.jl, disjoint_set.jl -> disjointSet.jl, binary_heap.jl -> binaryHeap.jl ?

**Comment by DanielArndt** [comment]
I agree that the names could use some standardization. However, rather than camel case, Julia base seems to standardize on all lower case (with the exception of some file names that use an underscore, presumably where it adds clarity). We should follow the same convention.

**Comment by sunoru** [comment]
I agree with you that using all characters in small case are the best. Actually I just suggested the choice for the least modification in this project. I think I would have a pull request for this.
