### ISSUE TITLE
Readthedocs not automatically updating

### ISSUE THREAD

**Issue by DanielArndt** [JuliaLang/DataStructures.jl#196]
@kmsquire @rawls238 As part of #179 , I don't believe the github webhooks were ever set up for readthedocs. 

When I merged in changes to the docs, I had to manually rebuild the docs. Someone with access to the "settings" tab in this repository needs to configure it, I believe.

**Comment by kmsquire** [comment]
I just gave you admin access.  Cheers!

**Comment by kmsquire** [comment]
@rawls238, you now have admin access as well.

**Comment by kmsquire** [comment]
(Post back if something additional is needed for RTD configuration.)

**Comment by DanielArndt** [comment]
Great, thanks. 

I added the webhook, and the test seems to work. Closing.
