### ISSUE TITLE
Doesn't precompile in 0.5?

### ISSUE THREAD

**Issue by sgt101** [JuliaLang/DataStructures.jl#200]
Hi, 

I'm trying out the 0.5 dev branch and I'm getting a no go for using Gadfly because of the Datastructures dependency. 

The error is: space before "(" not allowed in "OrderedDict{K} (" 
at line 414 of hashdict

Guess 0.5 will break a lot of things if the space thing isn't sorted!

**Comment by DanielArndt** [comment]
By dev branch, do you mean the master branch? If so, make sure you `git pull` to get the latest.

I believe this was fixed in #190 but it's hard to tell what line is actually causing you issues.

**Comment by DanielArndt** [comment]
@sgt101 If you have any further information to suggest that this problem exists in master, please re-open. Otherwise, using the latest tagged version (v0.4.3) will only give you support for Julia 0.4.

**Comment by kmsquire** [comment]
We could probably tag a new version...
