### ISSUE TITLE
Circular buffer / ring buffer

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/DataStructures.jl#201]
Hello,

a circular buffer / ring buffer could be a nice feature.

https://en.wikipedia.org/wiki/Circular_buffer

I noticed https://github.com/kmsquire/RingBuffer.jl
but it seems to be [broken](https://github.com/kmsquire/RingBuffer.jl/issues/2).

Kind regards

**Comment by tbreloff** [comment]
There's a simple implementation here: https://github.com/JuliaLang/DataStructures.jl/blob/master/src/circular_buffer.jl

**Comment by scls19fr** [comment]
Thanks @tbreloff 
Maybe it should be add to README.rst and to doc.
