### ISSUE TITLE
Tests fail on v0.5

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/DataStructures.jl#209]
```
Error During Test
  Test threw an exception of type UndefVarError
  Expression: contains(sprint(show,complement(IntSet())),"...,")
  UndefVarError: complement not defined
   in include_from_node1(::String) at ./loading.jl:426
   in macro expansion; at /Users/ranjan/.julia/v0.5/DataStructures/test/runtests.jl:30 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:426
   in process_options(::Base.JLOptions) at ./client.jl:262
   in _start() at ./client.jl:318
ERROR: LoadError: LoadError: There was an error during testing
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Error) at ./test.jl:397
 in do_test(::Base.Test.Threw, ::Expr) at ./test.jl:281
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at /Users/ranjan/.julia/v0.5/DataStructures/test/runtests.jl:30 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /Users/ranjan/.julia/v0.5/DataStructures/test/test_int_set.jl, in expression starting on line 17
while loading /Users/ranjan/.julia/v0.5/DataStructures/test/runtests.jl, in expression starting on line 27
```

**Comment by phaverty** [comment]
Base no longer exports (or defines) complement and complement! for IntSet.

**Comment by ranjanan** [comment]
Yes, it was deprecated in v0.4 and now no longer included in v0.5. Do you think a good way to tackle it is to include the original `complement` source code in this package? I can put together a PR, if need be.

**Comment by phaverty** [comment]
That sounds reasonable to me. But, I have to imagine someone has a plan for
what is supposed to happen here.

Another option would be to just drop the two tests that uses complement. It
looks like that's the only place it comes up. Maybe the intention of the
relevant authors is just that complement ceases to exist.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by ranjanan** [comment]
Ah, okay. I guess I'll wait for a contributor to chime in.

**Comment by kmsquire** [comment]
See https://github.com/JuliaLang/julia/pull/10065#issuecomment-123369017

Starting at that comment and reading down, it seems that copying the old code here should be fine.

**Comment by ranjanan** [comment]
Yeah. I agree. I'll write up a PR doing the same. Thanks!
