### ISSUE TITLE
Should there be conversion from Dict to OrderedDict?

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/DataStructures.jl#216]
Since `convert(Vector{Int}, Set([1,2,3]))` is not defined, shouldn't `convert(OrderedDict{Int, Int}, Dict(1=>2, 3=>4))` also be undefined? `OrderedDict` cares about the ordering, but the conversion gives it a random one, which isn't meaningful.

**Comment by rawls238** [comment]
It potentially could though if the keys are sortable. Perhaps we should change this behavior to throw an error if the keys aren't sortable but if the keys are sortable then we can use that ordering to order the `OrderedDict`?

**Comment by cstjean** [comment]
My main issue is with this 

```julia
type ClassRoom
   student_age::OrderedDict{String, Int}
end

cr = ClassRoom(Dict("Jim"=>8, "Bob"=>9))
...
for (name, age) in cr.student_age::OrderedDict   # subtly wrong
...
end
```

so picking a sorted order could work, but IMHO if some API expects an ordering, then passing an unordered container should be a mistake.

**Comment by kmsquire** [comment]
I actually agree with @cstjean.  I think arbitrarily picking sorted order might suggest that OrderedDicts are sorted (which they are, e.g., in C++).  If someone actually wants the keys to be sorted, they should use a SortedDict.

(There should be a good error message if this conversion is attempted.)

**Comment by rawls238** [comment]
that seems like reasonable behavior, perhaps we could have the error message point to using SortedDict instead of OrderedDict?

**Comment by cstjean** [comment]
Working on this issue now. I suppose we want to keep the conversion from `SortedDict` and other ordered associatives. `SortedDict` is defined after `OrderedDict`, so I can't refer to it in `ordered_dict.jl`. Is it better to:

- Define an `OrderedAssociative` abstract type?
- Define the conversion to OrderedDict in `sorted_dict.jl`?
- Define `isorderedassociativetype(::Type{SortedDict}) = true` and warn when it's false in  `convert(::Type{OrderedDict}, ...)`?

**Comment by kmsquire** [comment]
I like the last option, although I would make it something like `isordered` or `has_order`.

Other reasonable options:
* Defining the conversion to `OrderedDict` in `sorted_dict.jl` (as you suggested) 
* Reordering the imports so that `SortedDict` is defined first
