### ISSUE TITLE
Feature request: a function to get the handle when peeking a MutableBinaryHeap with `top`

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/DataStructures.jl#217]
This is basically what I'm asking for:

``` julia
function top_with_handle(heap::MutableBinaryHeap)
    el = theap.nodes[1]
    t, i = el.value, el.handle
    return t, i
end
```

This is especially useful to know what element was picked, in order to mutate it afterwards with `update!`. I need it for the particular case of `MutableBinaryHeap`, but I reckon it may be useful for other cases as well.

I could submit a PR with that implementation if there is interest. I'm not sure about the name though, suggestions are welcome.

**Comment by rawls238** [comment]
seems reasonable, feel free to put up a PR but why not just return the entire node?
