### ISSUE TITLE
Added feature: ordertype for sorted collections

### ISSUE THREAD

**Issue by neveritt** [JuliaLang/DataStructures.jl#226]
When including a `SortedDict` in a custom type, I found myself needing the following functionality to get the type of `Ordering` :

```
ordtype{K,D,Ord <: Ordering}(m::SortedDict{K,D,Ord}) = Ord
```

This is similar to what is already available for the other type parameters through `valtype` and `keytype`:

```
keytype{K,D,Ord <: Ordering}(m::SortedDict{K,D,Ord}) = K
valtype{K,D,Ord <: Ordering}(m::SortedDict{K,D,Ord}) = D
```

However, I noticed that `ordtype` is not exported by `Base`. Is there a reason for not including this functionality?

If of use, I would be glad to make a PR and include the corresponding one-liners for `SortedDict`, `SortedMultiDict` and `SortedSet`

**Comment by kmsquire** [comment]
This sounds very reasonable.  A PR would great!
