### ISSUE TITLE
Pushing to heap does not return heap

### ISSUE THREAD

**Issue by tawheeler** [JuliaLang/DataStructures.jl#235]
I just noticed that calling `push!` on a binary heap does not return the modified heap, as is convention.

```
using DataStructures
h = binary_minheap(Int)
push!(h, 1)
```

**Comment by kmsquire** [comment]
Should be an easy fix. Could you submit a PR?

**Comment by ararslan** [comment]
Fixed by #236?

**Comment by tawheeler** [comment]
Yessir
