### ISSUE TITLE
Empty set as default in defaultdict

### ISSUE THREAD

**Issue by ymer** [JuliaLang/DataStructures.jl#242]
I'm quite sure I used to be able to do this in an earlier version:

d = DefaultDict(Set)
push!(d[0], 1)

Now it gives this error message:
LoadError: MethodError: no method matching push!(::Type{Set}, ::Int64)

**Comment by kmsquire** [comment]
This works for me on Julia 0.5.  What version of Julia are you using?

**Comment by kmsquire** [comment]
(And on Julia 0.6)

**Comment by ymer** [comment]
I was using Julia 0.5. But I cannot recreate it now.

**Comment by kmsquire** [comment]
Thanks fir checking. 

If you're concerned about performance, you should add type parameters to both the DefaultDict and the Set. 

Closing for now. Please reopen if you rediscover a way to consistently reproduce this issue. Thanks for reporting it!
