### ISSUE TITLE
UndefRefError after removing keys from OrderedDict

### ISSUE THREAD

**Issue by pearcemc** [JuliaLang/DataStructures.jl#245]
Hi, I came across this while trying to use OrderedDict to maintain a maximum dict size.

```julia
julia> od = OrderedDict{String,Int64}()
DataStructures.OrderedDict{String,Int64} with 0 entries

julia> for i in 1:256
       if i>100
         pop!(od, od.keys[1])
       end
       od[string(Char(i))] = i
       end
ERROR: UndefRefError: access to undefined reference
 in getindex(::Array{String,1}, ::Int64) at ./array.jl:386
 in macro expansion; at ./REPL[196]:3 [inlined]
 in anonymous at ./<missing>:?

julia> od.keys
101-element Array{String,1}:
 #undef   
    "\x02"
    "\x03"
```

Perhaps I am just not using the structure properly, comments appreciated.

**Comment by yuyichao** [comment]
You should never access the field of any types in other packages. You can use `first` to get the first kv pair.

**Comment by kmsquire** [comment]
Just to clarify, here, `keys` is a hash table, and so most of the elements will be undefined.  You can use `keys(od)` to get an iterator over the keys, and `collect(keys(od))` to get a list of keys.
