### ISSUE TITLE
provide == as well as isequal for Julia 0.3

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/DataStructures.jl#34]
Currently, you are providing an `isequal` method for various types.   In Julia 0.3, you will *also* need to provide `==`.  See JuliaLang/julia#6833.

(In Julia 0.2, `==` called `isequal` by default, so providing `isequal` was enough.  In Julia 0.3, however, these two functions are swapped: `isequal` calls `==` by default.  So overriding `isequal` is not enough to make things like `!=` or `==` work.   In order to remain backward-compatible with Julia 0.2, you will need to provide *both* methods.)

**Comment by garrison** [comment]
Bump.  It is no longer necessary to support Julia 0.2, so fixing this should now be simpler. I believe the `isequal` call in `orderedset.jl` can be changed to `==`, but I am not sure what else should be replaced elsewhere.

**Comment by garrison** [comment]
#78 is a work-in-progress pull request.
