### ISSUE TITLE
OrderedSet not necessarily ordered

### ISSUE THREAD

**Issue by poulson** [JuliaLang/DataStructures.jl#72]
```
using DataStructures
set = OrderedSet{Int}()
push!(set,5)
push!(set,8)
push!(set,7)
push!(set,6)
for j in set
  println(j)
end
```

outputs 5, 8, 7, 6.

I was quite surprised by this behavior, as I had assumed that the *ordered* set would be iterated through in an ordered manner.

Is there a preferred different way to iterate through the set?

**Comment by simonster** [comment]
An OrderedSet gives elements in the order they were added. What you seem want is a SortedSet, which should be easy to implement on top of a SortedDict once #71 is merged.

**Comment by poulson** [comment]
Thanks, in hindsight the documentation is clear. Sorry for the confusion!
