### ISSUE TITLE
tree.jl types not being exported

### ISSUE THREAD

**Issue by mtabor150** [JuliaLang/DataStructures.jl#76]
Any reason why the tree.jl types are not currently being exported?

**Comment by kmsquire** [comment]
Really that no one has gotten around to it.  Would you be able to make a pull request?

**Comment by mtabor150** [comment]
Pull request #79 has the changes.

**Comment by kmsquire** [comment]
Closing this.  See my comments in https://github.com/JuliaLang/DataStructures.jl/pull/79#issuecomment-167917342.
