### ISSUE TITLE
Cannot break tests

### ISSUE THREAD

**Issue by gideonite** [JuliaLang/DataStructures.jl#92]
I've been running tests like this:

```sh
julia test/runtests.jl
```

But when I add the line 
```jl
@test true == false
```
into any one of the tests, everything passes.

Clearly, I'm a bit confused. Perhaps I'm running the tests incorrectly?

**Comment by hayd** [comment]
I can't replicate this. (Perhaps that means it's since been fixed??)

**Comment by DanielArndt** [comment]
I've been able to run the tests fine, so I'm assuming it is fixed or was caused by something else.

**Comment by gideonite** [comment]
Just tried rerunning the tests as I originally did, `julia test/runtests.jl` and got this error:

```
/tmp/DataStructures.jl/test/test_deque.jl ...
/tmp/DataStructures.jl/test/test_sortedcontainers.jl ...
ERROR: LoadError: LoadError: test failed: Tuple{Int64,Float64} == Pair{Int64,Float64}
 in expression: tpr == tuple_or_pair(Int,Float64)
 in default_handler at test.jl:30
 in do_test at test.jl:53
 in test2 at /tmp/DataStructures.jl/test/test_sortedcontainers.jl:460
 [inlined code] from /tmp/DataStructures.jl/test/runtests.jl:19
 in anonymous at no file:0
while loading /tmp/DataStructures.jl/test/test_sortedcontainers.jl, in expression starting on line 1702
```

I'm using julia version 0.4.2. I must be doing something wrong then? @hayd How did you run tests?

**Comment by DanielArndt** [comment]
I just did a `git pull` on master, verified my remote was set correctly, and ran the tests the same way, everything seemed to work fine... strange. Also julia 0.4.2.

**Comment by hayd** [comment]
@gideonite I ran the tests like you did:

    julia test/runtests.jl

I wonder if this is due to you having a different repository for DataStructures (one in `tmp` and one in `.julia/0.4` - where the library is loaded from)? The Pair/Tuple error definitely looks like you're running an older version of DataStructures (so perhaps try `Pkg.update`)...

**Comment by gideonite** [comment]
Yes, I think that is indeed the issue. What is the workflow for developing
Julia modules?

**Comment by hayd** [comment]
I usually just do it from .julia, however that's not ideal for working with multiple versions. I've spoken to a few people who symlink the directory: so it's in `my_projects/wherever/DataStructures.jl/` but symlinked to `.julia/0.4/DataStructures/` and `.julia/0.5/DataStructures/` etc.

Perhaps it's worth asking this on the julia-users mailing list :)
